# Site settings
title: Pok&eacute;pon Center
author: Silverweed
email: silverweed1991@gmail.com 
host: silverjail.jail
description: > # this means to ignore newlines until "baseurl:"
  A Pok&eacute;mon-like multiplayer battle simulator with ponies - <a href=
  'https://github.com/silverweed/pokepon-center'>GitHub</a>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pokepon.center" # the base hostname & protocol for your site
github_username:  silverweed
timezone: Europe/Rome
exclude: [ util ]

# Build settings
markdown: kramdown

# Front Matter defaults
defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
            author: "silverweed"

